[package]
name = "cube_spec_error"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst" }
amethyst_gltf = { git = "https://github.com/amethyst/amethyst" }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
